# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#files: 'src/.*'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-yaml
    -   id: name-tests-test
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus"]
-   repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
    -   id: pylama
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        name: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
#-   repo: https://github.com/psf/black
#    rev: 23.9.1
#    hooks:
#    -   id: black
#        args: ["-S"]
