class BlockType:

    NONE_BLOCKED = "NONE_BLOCKED"
    BLOCKED_BY_ADMIN = "BLOCKED_BY_ADMIN"
    INVALID_LOGIN = "TOO_MANY_LOGIN_FAILED_ATTEMPTS_BLOCKED"
    INVALID_OTP = "TOO_MANY_OTP_FAILED_ATTEMPTS_BLOCKED"
    INVALID_EMAIL = "TOO_MANY_EMAIL_FAILED_ATTEMPTS_BLOCKED"
    INVALID_PIN = "TOO_MANY_PIN_FAILED_ATTEMPTS_BLOCKED"
